openapi: 3.0.0
info:
  title: BlazePHP Secure API
  version: 1.0.0
paths:
  /api/users:
    get:
      summary: Get all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of users
    post:
      summary: Create new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role_id:
                  type: integer
      responses:
        '200':
          description: User created
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT